# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BGjzmVHrwsCDP7MDTjnKeK_D6D6Hc1l
"""



import os, glob, shutil, random, warnings
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import cv2
warnings.filterwarnings('ignore')

print("✅ Setup done")

import kagglehub

path = kagglehub.dataset_download("meowmeowmeowmeowmeow/gtsrb-german-traffic-sign")
print("📁 Dataset path:", path)

def find_dir(base, name):
    for root, dirs, _ in os.walk(base):
        for d in dirs:
            if d.lower() == name.lower():
                return os.path.join(root, d)
    return None

def find_file(base, name):
    for root, _, files in os.walk(base):
        for f in files:
            if f.lower() == name.lower():
                return os.path.join(root, f)
    return None

TRAIN_ROOT = find_dir(path, 'Train')
TEST_ROOT  = find_dir(path, 'Test')
TEST_CSV   = find_file(path, 'Test.csv')

print(TRAIN_ROOT, TEST_ROOT, TEST_CSV)

print("Classes:", len(os.listdir(TRAIN_ROOT)))

BASE = "/content/gtsrb_yolo"

for split in ["train", "val", "test"]:
    os.makedirs(f"{BASE}/{split}/images", exist_ok=True)
    os.makedirs(f"{BASE}/{split}/labels", exist_ok=True)

# Train → split
for cid in range(43):
    class_dir = os.path.join(TRAIN_ROOT, str(cid))
    imgs = glob.glob(os.path.join(class_dir, "*.ppm")) + \
           glob.glob(os.path.join(class_dir, "*.png"))

    random.shuffle(imgs)
    split_idx = int(0.8 * len(imgs))

    for i, img_path in enumerate(imgs):
        img = cv2.imread(img_path)
        h, w = img.shape[:2]

        # full image bbox (classification → detection trick)
        label = f"{cid} 0.5 0.5 1.0 1.0"

        split = "train" if i < split_idx else "val"

        fname = os.path.basename(img_path)
        new_img = f"{BASE}/{split}/images/{cid}_{fname}"
        new_lbl = f"{BASE}/{split}/labels/{cid}_{fname.replace('.ppm','.txt').replace('.png','.txt')}"

        shutil.copy(img_path, new_img)

        with open(new_lbl, "w") as f:
            f.write(label)

# Test images
for img_path in glob.glob(os.path.join(TEST_ROOT, "*.ppm")):
    fname = os.path.basename(img_path)
    shutil.copy(img_path, f"{BASE}/test/images/{fname}")

print("✅ YOLO dataset ready")

names = [f"class_{i}" for i in range(43)]

yaml_content = f"""
path: {BASE}
train: train/images
val: val/images
test: test/images

nc: 43
names: {names}
"""

YAML_PATH = f"{BASE}/dataset.yaml"

with open(YAML_PATH, "w") as f:
    f.write(yaml_content)

print("✅ YAML created")
print(yaml_content)

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

model.train(
    data=YAML_PATH,
    epochs=5,
    imgsz=640,
    batch=32,
    device=0,
    project="/content/gtsrb_runs",
    name="yolo11_gtsrb",
    exist_ok=True
)

model = YOLO("/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt")

metrics = model.val(data=YAML_PATH)

print("mAP50:", metrics.box.map50)
print("Precision:", metrics.box.mp)
print("Recall:", metrics.box.mr)

df = pd.read_csv("/content/gtsrb_runs/yolo11_gtsrb/results.csv")

plt.plot(df["metrics/mAP50(B)"])
plt.title("mAP50")
plt.show()

from google.colab import files

uploaded = files.upload()

for fname in uploaded:
    path = f"/content/{fname}"

    results = model.predict(path, conf=0.35)[0]

    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    for box in results.boxes:
        x1,y1,x2,y2 = map(int, box.xyxy[0])
        cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)

    plt.imshow(img)
    plt.axis("off")
    plt.show()

CLASS_NAMES = [
"Speed limit (20km/h)",
"Speed limit (30km/h)",
"Speed limit (50km/h)",
"Speed limit (60km/h)",
"Speed limit (70km/h)",
"Speed limit (80km/h)",
"End of speed limit (80km/h)",
"Speed limit (100km/h)",
"Speed limit (120km/h)",
"No passing",
"No passing >3.5t",
"Right-of-way at intersection",
"Priority road",
"Yield",
"Stop",
"No vehicles",
"No vehicles >3.5t",
"No entry",
"General caution",
"Dangerous curve left",
"Dangerous curve right",
"Double curve",
"Bumpy road",
"Slippery road",
"Road narrows right",
"Road work",
"Traffic signals",
"Pedestrians",
"Children crossing",
"Bicycles crossing",
"Beware of ice/snow",
"Wild animals crossing",
"End of all limits",
"Turn right ahead",
"Turn left ahead",
"Ahead only",
"Go straight or right",
"Go straight or left",
"Keep right",
"Keep left",
"Roundabout mandatory",
"End of no passing",
"End of no passing >3.5t"
]

yaml_content = f"""
path: {BASE}
train: train/images
val: val/images
test: test/images

nc: 43
names: {CLASS_NAMES}
"""

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

model = YOLO("/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt")

def detect_sign(image_path):
    results = model.predict(image_path, conf=0.35)[0]

    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    print("\n🚦 DETECTION RESULTS")
    print("="*40)

    for box in results.boxes:
        cls_id = int(box.cls.item())
        conf   = float(box.conf.item())

        label  = CLASS_NAMES[cls_id]

        x1,y1,x2,y2 = map(int, box.xyxy[0])

        # draw box
        cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)

        # show label
        text = f"{label} ({conf:.2f})"
        cv2.putText(img, text, (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                    (255,255,255), 2)

        # print result
        print(f"➡️ {label} | Confidence: {conf:.2f}")

    plt.imshow(img)
    plt.axis("off")
    plt.show()

from google.colab import files
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

# ✅ Load trained model
MODEL_PATH = "/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt"
model = YOLO(MODEL_PATH)

# ✅ Class names (GTSRB)
CLASS_NAMES = [
"Speed limit (20km/h)","Speed limit (30km/h)","Speed limit (50km/h)",
"Speed limit (60km/h)","Speed limit (70km/h)","Speed limit (80km/h)",
"End of speed limit (80km/h)","Speed limit (100km/h)","Speed limit (120km/h)",
"No passing","No passing >3.5t","Right-of-way at intersection","Priority road",
"Yield","Stop","No vehicles","No vehicles >3.5t","No entry","General caution",
"Dangerous curve left","Dangerous curve right","Double curve","Bumpy road",
"Slippery road","Road narrows right","Road work","Traffic signals","Pedestrians",
"Children crossing","Bicycles crossing","Beware of ice/snow","Wild animals crossing",
"End of all limits","Turn right ahead","Turn left ahead","Ahead only",
"Go straight or right","Go straight or left","Keep right","Keep left",
"Roundabout mandatory","End of no passing","End of no passing >3.5t"
]

# 🎯 Detection function
def detect_sign(image_path):
    results = model.predict(image_path, conf=0.35)[0]

    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    print("\n🚦 TRAFFIC SIGN DETECTION")
    print("="*45)

    if len(results.boxes) == 0:
        print("❌ No sign detected")
        return

    for box in results.boxes:
        cls_id = int(box.cls.item())
        conf   = float(box.conf.item())
        label  = CLASS_NAMES[cls_id]

        x1,y1,x2,y2 = map(int, box.xyxy[0])

        # Draw box
        cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)

        # Label text
        text = f"{label} ({conf:.2f})"
        cv2.putText(img, text, (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6,
                    (255,255,255), 2)

        # Print result
        print(f"➡️ {label} | Confidence: {conf:.2f}")

    print("="*45)

    plt.figure(figsize=(10,7))
    plt.imshow(img)
    plt.axis("off")
    plt.show()


# 📂 Upload & run
print("📤 Upload a traffic sign image:")
uploaded = files.upload()

for fname in uploaded:
    path = f"/content/{fname}"
    with open(path, "wb") as f:
        f.write(uploaded[fname])

    detect_sign(path)

from google.colab import files
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

# ✅ Load trained model
MODEL_PATH = "/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt"
model = YOLO(MODEL_PATH)

# ✅ Class names (GTSRB)
CLASS_NAMES = [
"Speed limit (20km/h)","Speed limit (30km/h)","Speed limit (50km/h)",
"Speed limit (60km/h)","Speed limit (70km/h)","Speed limit (80km/h)",
"End of speed limit (80km/h)","Speed limit (100km/h)","Speed limit (120km/h)",
"No passing","No passing >3.5t","Right-of-way at intersection","Priority road",
"Yield","Stop","No vehicles","No vehicles >3.5t","No entry","General caution",
"Dangerous curve left","Dangerous curve right","Double curve","Bumpy road",
"Slippery road","Road narrows right","Road work","Traffic signals","Pedestrians",
"Children crossing","Bicycles crossing","Beware of ice/snow","Wild animals crossing",
"End of all limits","Turn right ahead","Turn left ahead","Ahead only",
"Go straight or right","Go straight or left","Keep right","Keep left",
"Roundabout mandatory","End of no passing","End of no passing >3.5t"
]

# 🎯 Detection function
def detect_sign(image_path):
    results = model.predict(image_path, conf=0.35)[0]

    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    print("\n🚦 TRAFFIC SIGN DETECTION")
    print("="*45)

    if len(results.boxes) == 0:
        print("❌ No sign detected")
        return

    for box in results.boxes:
        cls_id = int(box.cls.item())
        conf   = float(box.conf.item())
        label  = CLASS_NAMES[cls_id]

        x1,y1,x2,y2 = map(int, box.xyxy[0])

        # Draw box
        cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)

        # Label text
        text = f"{label} ({conf:.2f})"
        cv2.putText(img, text, (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6,
                    (255,255,255), 2)

        # Print result
        print(f"➡️ {label} | Confidence: {conf:.2f}")

    print("="*45)

    plt.figure(figsize=(10,7))
    plt.imshow(img)
    plt.axis("off")
    plt.show()


# 📂 Upload & run
print("📤 Upload a traffic sign image:")
uploaded = files.upload()

for fname in uploaded:
    path = f"/content/{fname}"
    with open(path, "wb") as f:
        f.write(uploaded[fname])

    detect_sign(path)

from google.colab import files
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

# ✅ Load trained model
MODEL_PATH = "/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt"
model = YOLO(MODEL_PATH)

# ✅ Class names (GTSRB)
CLASS_NAMES = [
"Speed limit (20km/h)","Speed limit (30km/h)","Speed limit (50km/h)",
"Speed limit (60km/h)","Speed limit (70km/h)","Speed limit (80km/h)",
"End of speed limit (80km/h)","Speed limit (100km/h)","Speed limit (120km/h)",
"No passing","No passing >3.5t","Right-of-way at intersection","Priority road",
"Yield","Stop","No vehicles","No vehicles >3.5t","No entry","General caution",
"Dangerous curve left","Dangerous curve right","Double curve","Bumpy road",
"Slippery road","Road narrows right","Road work","Traffic signals","Pedestrians",
"Children crossing","Bicycles crossing","Beware of ice/snow","Wild animals crossing",
"End of all limits","Turn right ahead","Turn left ahead","Ahead only",
"Go straight or right","Go straight or left","Keep right","Keep left",
"Roundabout mandatory","End of no passing","End of no passing >3.5t"
]

# 🎯 Detection function
def detect_sign(image_path):
    results = model.predict(image_path, conf=0.35)[0]

    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    print("\n🚦 TRAFFIC SIGN DETECTION")
    print("="*45)

    if len(results.boxes) == 0:
        print("❌ No sign detected")
        return

    for box in results.boxes:
        cls_id = int(box.cls.item())
        conf   = float(box.conf.item())
        label  = CLASS_NAMES[cls_id]

        x1,y1,x2,y2 = map(int, box.xyxy[0])

        # Draw box
        cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)

        # Label text
        text = f"{label} ({conf:.2f})"
        cv2.putText(img, text, (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6,
                    (255,255,255), 2)

        # Print result
        print(f"➡️ {label} | Confidence: {conf:.2f}")

    print("="*45)

    plt.figure(figsize=(10,7))
    plt.imshow(img)
    plt.axis("off")
    plt.show()


# 📂 Upload & run
print("📤 Upload a traffic sign image:")
uploaded = files.upload()

for fname in uploaded:
    path = f"/content/{fname}"
    with open(path, "wb") as f:
        f.write(uploaded[fname])

    detect_sign(path)

from google.colab import files
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

# ✅ Load trained model
MODEL_PATH = "/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt"
model = YOLO(MODEL_PATH)

# ✅ Class names (GTSRB)
CLASS_NAMES = [
"Speed limit (20km/h)","Speed limit (30km/h)","Speed limit (50km/h)",
"Speed limit (60km/h)","Speed limit (70km/h)","Speed limit (80km/h)",
"End of speed limit (80km/h)","Speed limit (100km/h)","Speed limit (120km/h)",
"No passing","No passing >3.5t","Right-of-way at intersection","Priority road",
"Yield","Stop","No vehicles","No vehicles >3.5t","No entry","General caution",
"Dangerous curve left","Dangerous curve right","Double curve","Bumpy road",
"Slippery road","Road narrows right","Road work","Traffic signals","Pedestrians",
"Children crossing","Bicycles crossing","Beware of ice/snow","Wild animals crossing",
"End of all limits","Turn right ahead","Turn left ahead","Ahead only",
"Go straight or right","Go straight or left","Keep right","Keep left",
"Roundabout mandatory","End of no passing","End of no passing >3.5t"
]

# 🎯 Detection function
def detect_sign(image_path):
    results = model.predict(image_path, conf=0.35)[0]

    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    print("\n🚦 TRAFFIC SIGN DETECTION")
    print("="*45)

    if len(results.boxes) == 0:
        print("❌ No sign detected")
        return

    for box in results.boxes:
        cls_id = int(box.cls.item())
        conf   = float(box.conf.item())
        label  = CLASS_NAMES[cls_id]

        x1,y1,x2,y2 = map(int, box.xyxy[0])

        # Draw box
        cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)

        # Label text
        text = f"{label} ({conf:.2f})"
        cv2.putText(img, text, (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6,
                    (255,255,255), 2)

        # Print result
        print(f"➡️ {label} | Confidence: {conf:.2f}")

    print("="*45)

    plt.figure(figsize=(10,7))
    plt.imshow(img)
    plt.axis("off")
    plt.show()


# 📂 Upload & run
print("📤 Upload a traffic sign image:")
uploaded = files.upload()

for fname in uploaded:
    path = f"/content/{fname}"
    with open(path, "wb") as f:
        f.write(uploaded[fname])

    detect_sign(path)

from ultralytics import YOLO
import cv2
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

# Load model
model = YOLO("/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt")

CLASS_NAMES = [
"Speed limit (20km/h)","Speed limit (30km/h)","Speed limit (50km/h)",
"Speed limit (60km/h)","Speed limit (70km/h)","Speed limit (80km/h)",
"End of speed limit (80km/h)","Speed limit (100km/h)","Speed limit (120km/h)",
"No passing","No passing >3.5t","Right-of-way at intersection","Priority road",
"Yield","Stop","No vehicles","No vehicles >3.5t","No entry","General caution",
"Dangerous curve left","Dangerous curve right","Double curve","Bumpy road",
"Slippery road","Road narrows right","Road work","Traffic signals","Pedestrians",
"Children crossing","Bicycles crossing","Beware of ice/snow","Wild animals crossing",
"End of all limits","Turn right ahead","Turn left ahead","Ahead only",
"Go straight or right","Go straight or left","Keep right","Keep left",
"Roundabout mandatory","End of no passing","End of no passing >3.5t"
]

# JS to capture image
def capture_image():
    js = Javascript('''
    async function takePhoto() {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = '📸 Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);

      stream.getTracks().forEach(track => track.stop());
      div.remove();

      return canvas.toDataURL('image/jpeg', 0.8);
    }
    takePhoto();
    ''')
    display(js)
    data = eval_js('takePhoto()')
    binary = b64decode(data.split(',')[1])
    return binary

# Capture
print("📷 Click capture to take image")
img_bytes = capture_image()

# Save image
with open("captured.jpg", "wb") as f:
    f.write(img_bytes)

# Detection
results = model.predict("captured.jpg", conf=0.35)[0]

img = cv2.imread("captured.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

print("\n🚦 DETECTION RESULT")
print("="*40)

for box in results.boxes:
    cls_id = int(box.cls.item())
    conf   = float(box.conf.item())
    label  = CLASS_NAMES[cls_id]

    x1,y1,x2,y2 = map(int, box.xyxy[0])

    cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
    cv2.putText(img,f"{label} ({conf:.2f})",(x1,y1-10),
                cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,255,255),2)

    print(f"➡️ {label} | {conf:.2f}")

plt.imshow(img)
plt.axis("off")
plt.show()

from ultralytics import YOLO
import cv2
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

# Load model
model = YOLO("/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt")

CLASS_NAMES = [
"Speed limit (20km/h)","Speed limit (30km/h)","Speed limit (50km/h)",
"Speed limit (60km/h)","Speed limit (70km/h)","Speed limit (80km/h)",
"End of speed limit (80km/h)","Speed limit (100km/h)","Speed limit (120km/h)",
"No passing","No passing >3.5t","Right-of-way at intersection","Priority road",
"Yield","Stop","No vehicles","No vehicles >3.5t","No entry","General caution",
"Dangerous curve left","Dangerous curve right","Double curve","Bumpy road",
"Slippery road","Road narrows right","Road work","Traffic signals","Pedestrians",
"Children crossing","Bicycles crossing","Beware of ice/snow","Wild animals crossing",
"End of all limits","Turn right ahead","Turn left ahead","Ahead only",
"Go straight or right","Go straight or left","Keep right","Keep left",
"Roundabout mandatory","End of no passing","End of no passing >3.5t"
]

# JS to capture image
def capture_image():
    js = Javascript('''
    async function takePhoto() {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = '📸 Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);

      stream.getTracks().forEach(track => track.stop());
      div.remove();

      return canvas.toDataURL('image/jpeg', 0.8);
    }
    takePhoto();
    ''')
    display(js)
    data = eval_js('takePhoto()')
    binary = b64decode(data.split(',')[1])
    return binary

# Capture
print("📷 Click capture to take image")
img_bytes = capture_image()

# Save image
with open("captured.jpg", "wb") as f:
    f.write(img_bytes)

# Detection
results = model.predict("captured.jpg", conf=0.35)[0]

img = cv2.imread("captured.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

print("\n🚦 DETECTION RESULT")
print("="*40)

for box in results.boxes:
    cls_id = int(box.cls.item())
    conf   = float(box.conf.item())
    label  = CLASS_NAMES[cls_id]

    x1,y1,x2,y2 = map(int, box.xyxy[0])

    cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
    cv2.putText(img,f"{label} ({conf:.2f})",(x1,y1-10),
                cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,255,255),2)

    print(f"➡️ {label} | {conf:.2f}")

plt.imshow(img)
plt.axis("off")
plt.show()

from ultralytics import YOLO
import cv2
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

# Load model
model = YOLO("/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt")

CLASS_NAMES = [
"Speed limit (20km/h)","Speed limit (30km/h)","Speed limit (50km/h)",
"Speed limit (60km/h)","Speed limit (70km/h)","Speed limit (80km/h)",
"End of speed limit (80km/h)","Speed limit (100km/h)","Speed limit (120km/h)",
"No passing","No passing >3.5t","Right-of-way at intersection","Priority road",
"Yield","Stop","No vehicles","No vehicles >3.5t","No entry","General caution",
"Dangerous curve left","Dangerous curve right","Double curve","Bumpy road",
"Slippery road","Road narrows right","Road work","Traffic signals","Pedestrians",
"Children crossing","Bicycles crossing","Beware of ice/snow","Wild animals crossing",
"End of all limits","Turn right ahead","Turn left ahead","Ahead only",
"Go straight or right","Go straight or left","Keep right","Keep left",
"Roundabout mandatory","End of no passing","End of no passing >3.5t"
]

# JS to capture image
def capture_image():
    js = Javascript('''
    async function takePhoto() {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = '📸 Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);

      stream.getTracks().forEach(track => track.stop());
      div.remove();

      return canvas.toDataURL('image/jpeg', 0.8);
    }
    takePhoto();
    ''')
    display(js)
    data = eval_js('takePhoto()')
    binary = b64decode(data.split(',')[1])
    return binary

# Capture
print("📷 Click capture to take image")
img_bytes = capture_image()

# Save image
with open("captured.jpg", "wb") as f:
    f.write(img_bytes)

# Detection
results = model.predict("captured.jpg", conf=0.35)[0]

img = cv2.imread("captured.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

print("\n🚦 DETECTION RESULT")
print("="*40)

for box in results.boxes:
    cls_id = int(box.cls.item())
    conf   = float(box.conf.item())
    label  = CLASS_NAMES[cls_id]

    x1,y1,x2,y2 = map(int, box.xyxy[0])

    cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
    cv2.putText(img,f"{label} ({conf:.2f})",(x1,y1-10),
                cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,255,255),2)

    print(f"➡️ {label} | {conf:.2f}")

plt.imshow(img)
plt.axis("off")
plt.show()

from ultralytics import YOLO
import cv2
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

# Load model
model = YOLO("/content/gtsrb_runs/yolo11_gtsrb/weights/best.pt")

CLASS_NAMES = [
"Speed limit (20km/h)","Speed limit (30km/h)","Speed limit (50km/h)",
"Speed limit (60km/h)","Speed limit (70km/h)","Speed limit (80km/h)",
"End of speed limit (80km/h)","Speed limit (100km/h)","Speed limit (120km/h)",
"No passing","No passing >3.5t","Right-of-way at intersection","Priority road",
"Yield","Stop","No vehicles","No vehicles >3.5t","No entry","General caution",
"Dangerous curve left","Dangerous curve right","Double curve","Bumpy road",
"Slippery road","Road narrows right","Road work","Traffic signals","Pedestrians",
"Children crossing","Bicycles crossing","Beware of ice/snow","Wild animals crossing",
"End of all limits","Turn right ahead","Turn left ahead","Ahead only",
"Go straight or right","Go straight or left","Keep right","Keep left",
"Roundabout mandatory","End of no passing","End of no passing >3.5t"
]

# JS to capture image
def capture_image():
    js = Javascript('''
    async function takePhoto() {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = '📸 Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);

      stream.getTracks().forEach(track => track.stop());
      div.remove();

      return canvas.toDataURL('image/jpeg', 0.8);
    }
    takePhoto();
    ''')
    display(js)
    data = eval_js('takePhoto()')
    binary = b64decode(data.split(',')[1])
    return binary

# Capture
print("📷 Click capture to take image")
img_bytes = capture_image()

# Save image
with open("captured.jpg", "wb") as f:
    f.write(img_bytes)

# Detection
results = model.predict("captured.jpg", conf=0.35)[0]

img = cv2.imread("captured.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

print("\n🚦 DETECTION RESULT")
print("="*40)

for box in results.boxes:
    cls_id = int(box.cls.item())
    conf   = float(box.conf.item())
    label  = CLASS_NAMES[cls_id]

    x1,y1,x2,y2 = map(int, box.xyxy[0])

    cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
    cv2.putText(img,f"{label} ({conf:.2f})",(x1,y1-10),
                cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,255,255),2)

    print(f"➡️ {label} | {conf:.2f}")

plt.imshow(img)
plt.axis("off")
plt.show()